travis:
  secure:
    BINSTAR_TOKEN: dFNwvYnYYac3DMUwC9FQ8XUpf7JuirymEUoDTxRSKY5rlaDaVhpgRnbU+wkYQ/j2MbIuHO+h4DgPoY7aAtgQCNZxFm2iBfNKP0FYXOpnhhAdN8AJ7Ew0k7mV5mCsup3zcTcoxV8DgdC8roecPA1Kxvu5vc8fauusFK4zrs/hDeNgrNsBOOXdZz4V5kO62gNqmXJvDAaxO91SdoeH59m16wd0wNp1zywYn70lS6C7sQBts8JgoqtvaqNR0RxSWNj+sxz8XYRAfCnom7bJD3NYBDvUubxwgMT8Mh09p+QG1Hw6Pmy7uJhDw4r1dkFFYNLZvtNDL+Lh+NHEESqUbRi82m7lFUnl4YovYlu/JHIiIxlCNirNF1nNBXV0ZsT4VYsajEfmc0pPjLoh6Pg4qiEySSXLgFG/gwuvcMb5r+HinXQqZXhYYR+0/5N5LpihVZQ2nY2bb08qFOhKbBa9n5jusi61CsSV0/+AMk7PyyeBh8fPVsRTRi6z+VPcj1tSUVDeYLjdATpPxRJr6HVAqA2Gy1aOvSJdLhj+FqWoV63KF4W6j1Q42NtIIcqj+ufrBU1+NdrAr35N2FbgZGH0O/4u7oHbcjGOXLpxaOPwxnNecWdYLoODn6N2jIpCaRJTmqNFr89l8PeoqUBwFD/mLqXTsqbQq/VLvF+tc6ZZkWWXq/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
